import express from 'express';
import protect from '../middleware/auth.js';
import { getProjects, createProject, getProject, updateProject, deleteProject } from '../controllers/projectController.js';
const router = express.Router();
router.use(protect);
router.get('/', getProjects);
router.post('/', createProject);
router.get('/:id', getProject);
router.put('/:id', updateProject);
router.delete('/:id', deleteProject);
export default router;